name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Bu iş akışını 'main' şubesine yapılan itmelerde çalıştırır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Kullandığınız Ruby sürümüne göre ayarlayın

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # GitHub Pages için kullanmak istediğiniz branch
        publish_dir: ./_site  # Jekyll site çıktısının bulunduğu dizin
